version: "3.7"
services:
  app:
    build: .
    volumes:
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./:/app
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: yeticave
